// AUTO-GENERATED by scripts/generate_from_canonical.py on 2026-06-12
// Source: data/canonical_parameters/feedstocks.yaml
// Merge these constants into calculatorEngine.ts to replace current BMP values.
// vs = VS/TS fraction (dry-weight basis) — use vs_of_ts_medio / 100.


export const SUGARCANE_STREAMS_CANONICAL = {
  bagaco: { bmp: 165.0, vs: 0.9, ch4: 0.55 },  // Bagaço de cana-de-açúcar
  palha: { bmp: 175.0, vs: 0.82, ch4: 0.55 },  // Palha de cana-de-açúcar
  vinhaca: { bmp: 160.0, vs: 0.6, ch4: 0.65 },  // Vinhaça de cana-de-açúcar
  torta: { bmp: 280.0, vs: 0.8, ch4: 0.60 },  // Torta de filtro
};

export const CROP_PARAMS_CANONICAL = {
  corn: { bmp: 230.0, vs: 0.86, ch4: 0.55 },  // Palha de milho
  soy: { bmp: 300.0, vs: 0.93, ch4: 0.55 },  // Casca de soja
  coffee: { bmp: 165.0, vs: 0.93, ch4: 0.58 },  // Casca de café
  citrus: { bmp: 230.0, vs: 0.88, ch4: 0.56 },  // Bagaço de citros
};
