#!/usr/bin/env python3
"""
generate_from_canonical.py
==========================
Single source of truth → all code layers.

Reads:
  data/canonical_parameters/feedstocks.yaml
  data/canonical_parameters/references.yaml

Writes (to stdout or --out-dir):
  backend/app/migrations/016_canonical_sync.sql
  backend/app/services/_canonical_biomass_configs.py   (import into biomass_availability.py)
  frontend/src/app/.../calculatorEngine.canonical.ts    (merge into calculatorEngine.ts)
  data/fde_all_residues_patch.json                      (patch for fde_all_residues.json)
  docs/data/PARAMETER_CITATIONS.md                      (human-readable citation table)

Usage:
  python scripts/generate_from_canonical.py
  python scripts/generate_from_canonical.py --out-dir cp2b-workspace/NewLook
  python scripts/generate_from_canonical.py --validate-only
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from datetime import date

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).parent.parent
FEEDSTOCKS_YAML = ROOT / "data" / "canonical_parameters" / "feedstocks.yaml"
REFERENCES_YAML = ROOT / "data" / "canonical_parameters" / "references.yaml"


# ─── Loaders ─────────────────────────────────────────────────────────────────

def load(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


# ─── Validation ──────────────────────────────────────────────────────────────

def validate(feedstocks: dict, references: dict) -> list[str]:
    """Return list of validation errors (empty = clean)."""
    errors: list[str] = []
    ref_ids = set(references.get("references", {}).keys())

    for code, fs in feedstocks.get("feedstocks", {}).items():
        for param in ("bmp", "ts", "vs_of_ts"):
            data = fs.get(param, {})
            if not data:
                errors.append(f"{code}.{param}: missing")
                continue
            for ref in data.get("refs", []):
                ref_id = ref["id"] if isinstance(ref, dict) else ref
                if ref_id not in ref_ids:
                    errors.append(f"{code}.{param}: unknown ref '{ref_id}'")

        bmp = fs.get("bmp", {})
        if bmp:
            if not (0 < bmp.get("min", 0) <= bmp.get("medio", 0) <= bmp.get("max", 9999)):
                errors.append(f"{code}.bmp: min/medio/max ordering violated")
            if bmp.get("medio", 0) > 1200:
                errors.append(f"{code}.bmp.medio={bmp['medio']}: exceeds 1200 NmL/gVS (fats ok; flag otherwise)")

        ts = fs.get("ts", {})
        vs = fs.get("vs_of_ts", {})
        if ts and vs:
            vs_wet = ts.get("medio", 0) * vs.get("medio", 0) / 100.0
            if vs_wet > 100:
                errors.append(f"{code}: derived vs_wet={vs_wet:.1f}% > 100% (impossible)")

    return errors


# ─── Derived helpers ──────────────────────────────────────────────────────────

def vs_wet(fs: dict) -> float:
    """VS as % wet weight = TS_medio × VS_of_TS_medio / 100."""
    ts = fs.get("ts", {}).get("medio", 0)
    vs = fs.get("vs_of_ts", {}).get("medio", 0)
    return round(ts * vs / 100.0, 2)


def first_url(code: str, fs: dict, references: dict) -> str:
    """Return the URL of the first cited reference for this feedstock's BMP."""
    refs = references.get("references", {})
    for ref_entry in fs.get("bmp", {}).get("refs", []):
        ref_id = ref_entry["id"] if isinstance(ref_entry, dict) else ref_entry
        ref = refs.get(ref_id, {})
        if ref.get("url"):
            return ref["url"]
    return "https://doi.org/NEEDS_CITATION"


# ─── SQL generator ────────────────────────────────────────────────────────────

SQL_HEADER = """\
-- =============================================================================
-- Migration 016: Canonical BMP synchronisation
-- Generated by scripts/generate_from_canonical.py on {date}
-- Source: data/canonical_parameters/feedstocks.yaml
-- DO NOT EDIT MANUALLY — re-run the generator to update.
-- =============================================================================
"""

def generate_sql(feedstocks: dict, references: dict) -> str:
    lines = [SQL_HEADER.format(date=date.today())]
    for code, fs in feedstocks.get("feedstocks", {}).items():
        bmp = fs.get("bmp", {})
        ts  = fs.get("ts", {})
        vs  = fs.get("vs_of_ts", {})
        if not (bmp and ts and vs):
            continue
        url = first_url(code, fs, references)
        lines.append(f"-- {fs.get('pt_name', code)}  |  ref: {url}")
        lines.append(
            f"UPDATE residuos SET\n"
            f"    bmp_min={bmp['min']}, bmp_medio={bmp['medio']}, bmp_max={bmp['max']},\n"
            f"    ts_min={ts['min']}, ts_medio={ts['medio']}, ts_max={ts['max']},\n"
            f"    vs_min={vs['min']}, vs_medio={vs['medio']}, vs_max={vs['max']}\n"
            f"WHERE codigo = '{code}';\n"
        )
    return "\n".join(lines)


# ─── Python config generator ──────────────────────────────────────────────────

# Map canonical code → service layer key (biomass_availability.py aggregate keys)
SERVICE_LAYER_MAP = {
    "BAGACO":        ("sugarcane", "agricultural"),
    "CASCA_SOJA":    ("soybean",   "agricultural"),
    "PALHA_MILHO":   ("corn",      "agricultural"),
    "CASCA_CAFE":    ("coffee",    "agricultural"),
    "BAGACO_CITROS": ("citrus",    "agricultural"),
    "ESTERCO_BOVINO":("cattle",    "livestock"),
    "DEJETOS_SUINO": ("swine",     "livestock"),
    "CAMA_AVIARIO":  ("poultry",   "livestock"),
    "FORSU":         ("rsu",       "urban"),
    "LODO_PRIMARIO": ("rpo",       "urban"),  # rpo = RPO / lodo aggregate
}

PY_HEADER = '''\
# AUTO-GENERATED by scripts/generate_from_canonical.py on {date}
# Source: data/canonical_parameters/feedstocks.yaml
# Import this block into biomass_availability.py to replace RESIDUE_BIOMASS_CONFIGS.
# VS values are wet-weight % (ts_medio × vs_of_ts_medio / 100).

from app.services.biomass_availability import ResidueBiomassConfig

RESIDUE_BIOMASS_CONFIGS_CANONICAL: tuple[ResidueBiomassConfig, ...] = (
'''

def generate_python(feedstocks: dict, references: dict) -> str:
    lines = [PY_HEADER.format(date=date.today())]
    seen_keys: set[str] = set()
    for code, fs in feedstocks.get("feedstocks", {}).items():
        if code not in SERVICE_LAYER_MAP:
            continue
        key, sector = SERVICE_LAYER_MAP[code]
        if key in seen_keys:
            continue
        seen_keys.add(key)
        bmp_v = fs["bmp"]["medio"]
        vs_v  = vs_wet(fs)
        url   = first_url(code, fs, references)
        lines.append(
            f'    # {fs.get("pt_name", code)} — {url}\n'
            f'    ResidueBiomassConfig("{key}", "{sector}", "{key}_biomass_tons_year",'
            f' "{key}_biogas_m3_year", {bmp_v}, {vs_v}),'
        )
    lines.append(")\n")
    return "\n".join(lines)


# ─── TypeScript constant generator ───────────────────────────────────────────

# Canonical code → TS calculator key and stream name
TS_LAYER_MAP = {
    "BAGACO":        ("SUGARCANE_STREAMS", "bagaco"),
    "PALHA":         ("SUGARCANE_STREAMS", "palha"),
    "VINHACA":       ("SUGARCANE_STREAMS", "vinhaca"),
    "TORTA_FILTRO":  ("SUGARCANE_STREAMS", "torta"),
    "PALHA_MILHO":   ("CROP_PARAMS",       "corn"),
    "CASCA_SOJA":    ("CROP_PARAMS",       "soy"),
    "CASCA_CAFE":    ("CROP_PARAMS",       "coffee"),
    "BAGACO_CITROS": ("CROP_PARAMS",       "citrus"),
}

TS_HEADER = """\
// AUTO-GENERATED by scripts/generate_from_canonical.py on {date}
// Source: data/canonical_parameters/feedstocks.yaml
// Merge these constants into calculatorEngine.ts to replace current BMP values.
// vs = VS/TS fraction (dry-weight basis) — use vs_of_ts_medio / 100.

"""

def generate_ts(feedstocks: dict) -> str:
    lines = [TS_HEADER.format(date=date.today())]

    # Sugarcane streams
    lines.append("export const SUGARCANE_STREAMS_CANONICAL = {")
    for code, (group, stream) in TS_LAYER_MAP.items():
        if group != "SUGARCANE_STREAMS":
            continue
        fs = feedstocks["feedstocks"].get(code)
        if not fs:
            continue
        bmp_v = fs["bmp"]["medio"]
        vs_v  = round(fs["vs_of_ts"]["medio"] / 100.0, 4)
        ch4_v = fs.get("ch4_pct", 55.0) / 100.0
        lines.append(f'  {stream}: {{ bmp: {bmp_v}, vs: {vs_v}, ch4: {ch4_v:.2f} }},  // {fs.get("pt_name", code)}')
    lines.append("};\n")

    # Crop params
    lines.append("export const CROP_PARAMS_CANONICAL = {")
    for code, (group, crop) in TS_LAYER_MAP.items():
        if group != "CROP_PARAMS":
            continue
        fs = feedstocks["feedstocks"].get(code)
        if not fs:
            continue
        bmp_v = fs["bmp"]["medio"]
        vs_v  = round(fs["vs_of_ts"]["medio"] / 100.0, 4)
        ch4_v = fs.get("ch4_pct", 55.0) / 100.0
        lines.append(f'  {crop}: {{ bmp: {bmp_v}, vs: {vs_v}, ch4: {ch4_v:.2f} }},  // {fs.get("pt_name", code)}')
    lines.append("};\n")

    return "\n".join(lines)


# ─── JSON patch generator ─────────────────────────────────────────────────────

def generate_json_patch(feedstocks: dict) -> list[dict]:
    """Generate a list of {codigo, bmp_value} patches for fde_all_residues.json."""
    patches = []
    for code, fs in feedstocks.get("feedstocks", {}).items():
        bmp_v = fs.get("bmp", {}).get("medio")
        if bmp_v is not None:
            patches.append({"codigo": code, "bmp_value": bmp_v})
    return patches


# ─── Citation table generator ─────────────────────────────────────────────────

MD_HEADER = """\
# PILAR-2b Parameter Citation Table

> Auto-generated on {date} from `data/canonical_parameters/feedstocks.yaml`
> and `data/canonical_parameters/references.yaml`.
> Edit those YAML files — do not edit this document directly.

| Code | Parameter | min | medio | max | Unit | Primary Reference | URL |
|------|-----------|-----|-------|-----|------|-------------------|-----|
"""

def generate_citation_table(feedstocks: dict, references: dict) -> str:
    refs = references.get("references", {})
    rows = [MD_HEADER.format(date=date.today())]

    for code, fs in feedstocks.get("feedstocks", {}).items():
        name = fs.get("pt_name", code)
        for param, label, unit in [
            ("bmp",      "BMP",   "NmL CH₄/gVS"),
            ("ts",       "TS",    "% wet weight"),
            ("vs_of_ts", "VS/TS", "% of TS"),
        ]:
            data = fs.get(param, {})
            if not data:
                continue
            min_v   = data.get("min", "—")
            med_v   = data.get("medio", "—")
            max_v   = data.get("max", "—")
            ref_entries = data.get("refs", [])
            if ref_entries:
                first = ref_entries[0]
                ref_id = first["id"] if isinstance(first, dict) else first
                ref = refs.get(ref_id, {})
                cite = f"{ref.get('authors','?').split(',')[0]} et al. ({ref.get('year','?')})"
                url  = ref.get("url", "NEEDS_URL")
            else:
                cite = "NEEDS_CITATION"
                url  = "NEEDS_URL"
            rows.append(
                f"| {code} | {label} | {min_v} | {med_v} | {max_v} | {unit} "
                f"| {cite} | [{url}]({url}) |"
            )

    return "\n".join(rows) + "\n"


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Generate all code layers from canonical YAML")
    parser.add_argument("--out-dir", default=str(ROOT),
                        help="Root of the NewLook workspace (default: auto-detect)")
    parser.add_argument("--validate-only", action="store_true",
                        help="Only validate YAML, do not write any files")
    args = parser.parse_args()

    out = Path(args.out_dir)

    print("Loading canonical parameters…")
    feedstocks  = load(FEEDSTOCKS_YAML)
    references  = load(REFERENCES_YAML)

    print("Validating…")
    errors = validate(feedstocks, references)
    if errors:
        print(f"\n{'='*60}\nVALIDATION ERRORS ({len(errors)}):\n{'='*60}")
        for e in errors:
            print(f"  ✗ {e}")
        if args.validate_only:
            sys.exit(1)
        print("\nProceeding despite errors (fix them for production).\n")
    else:
        print("  ✓ All references resolved, all ranges valid.")

    if args.validate_only:
        print("Validation complete.")
        return

    # SQL migration
    sql_path = out / "backend" / "app" / "migrations" / "016_canonical_sync.sql"
    sql_path.write_text(generate_sql(feedstocks, references), encoding="utf-8")
    print(f"  → {sql_path}")

    # Python config snippet
    py_path = out / "backend" / "app" / "services" / "_canonical_biomass_configs.py"
    py_path.write_text(generate_python(feedstocks, references), encoding="utf-8")
    print(f"  → {py_path}")

    # TypeScript constants
    ts_path = out / "frontend" / "src" / "app" / "[locale]" / "dashboard" / "technology-routes" / "calculatorEngine.canonical.ts"
    ts_path.parent.mkdir(parents=True, exist_ok=True)
    ts_path.write_text(generate_ts(feedstocks), encoding="utf-8")
    print(f"  → {ts_path}")

    # JSON patch
    patch = generate_json_patch(feedstocks)
    patch_path = out / "data" / "fde_all_residues_patch.json"
    patch_path.write_text(json.dumps(patch, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  → {patch_path} ({len(patch)} entries)")

    # Citation table
    md_path = out / "docs" / "data" / "PARAMETER_CITATIONS.md"
    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(generate_citation_table(feedstocks, references), encoding="utf-8")
    print(f"  → {md_path}")

    # Summary
    n = len(feedstocks.get("feedstocks", {}))
    print(f"\nDone — {n} feedstocks processed.")
    print("\nNext steps:")
    print("  1. Review 016_canonical_sync.sql and apply to Supabase.")
    print("  2. Copy _canonical_biomass_configs.py block into biomass_availability.py.")
    print("  3. Merge calculatorEngine.canonical.ts values into calculatorEngine.ts.")
    print("  4. Apply fde_all_residues_patch.json using scripts/apply_fde_patch.py (TBD).")


if __name__ == "__main__":
    main()
