-- =============================================================================
-- Migration 016: Canonical BMP synchronisation
-- Generated by scripts/generate_from_canonical.py on 2026-06-12
-- Source: data/canonical_parameters/feedstocks.yaml
-- DO NOT EDIT MANUALLY — re-run the generator to update.
-- =============================================================================

-- Bagaço de cana-de-açúcar  |  ref: https://doi.org/10.1016/j.indcrop.2021.113498
UPDATE residuos SET
    bmp_min=115.0, bmp_medio=165.0, bmp_max=220.0,
    ts_min=50.0, ts_medio=58.9, ts_max=66.0,
    vs_min=76.5, vs_medio=90.0, vs_max=97.0
WHERE codigo = 'BAGACO';

-- Palha de cana-de-açúcar  |  ref: https://doi.org/10.1016/j.indcrop.2021.113498
UPDATE residuos SET
    bmp_min=140.0, bmp_medio=175.0, bmp_max=250.0,
    ts_min=18.0, ts_medio=30.0, ts_max=55.0,
    vs_min=72.0, vs_medio=82.0, vs_max=92.0
WHERE codigo = 'PALHA';

-- Vinhaça de cana-de-açúcar  |  ref: https://doi.org/10.1016/j.rser.2015.01.022
UPDATE residuos SET
    bmp_min=90.0, bmp_medio=160.0, bmp_max=200.0,
    ts_min=1.0, ts_medio=3.0, ts_max=5.0,
    vs_min=45.0, vs_medio=60.0, vs_max=75.0
WHERE codigo = 'VINHACA';

-- Torta de filtro  |  ref: https://doi.org/10.15376/biores.11.3.6824-6841
UPDATE residuos SET
    bmp_min=200.0, bmp_medio=280.0, bmp_max=380.0,
    ts_min=28.0, ts_medio=38.0, ts_max=48.0,
    vs_min=68.0, vs_medio=80.0, vs_max=90.0
WHERE codigo = 'TORTA_FILTRO';

-- Bagaço de citros  |  ref: https://doi.org/10.1016/j.biortech.2014.07.074
UPDATE residuos SET
    bmp_min=170.0, bmp_medio=230.0, bmp_max=310.0,
    ts_min=10.0, ts_medio=18.0, ts_max=26.0,
    vs_min=82.0, vs_medio=88.0, vs_max=94.0
WHERE codigo = 'BAGACO_CITROS';

-- Cascas de citros  |  ref: https://doi.org/10.1016/j.biortech.2014.07.074
UPDATE residuos SET
    bmp_min=160.0, bmp_medio=210.0, bmp_max=290.0,
    ts_min=15.0, ts_medio=20.0, ts_max=28.0,
    vs_min=80.0, vs_medio=88.0, vs_max=94.0
WHERE codigo = 'CASCAS_CITROS';

-- Casca de café  |  ref: https://doi.org/10.1016/j.biteb.2021.100830
UPDATE residuos SET
    bmp_min=120.0, bmp_medio=165.0, bmp_max=220.0,
    ts_min=82.0, ts_medio=88.0, ts_max=93.0,
    vs_min=88.0, vs_medio=93.0, vs_max=97.0
WHERE codigo = 'CASCA_CAFE';

-- Polpa de café  |  ref: https://doi.org/10.1016/j.biteb.2021.100830
UPDATE residuos SET
    bmp_min=190.0, bmp_medio=245.0, bmp_max=290.0,
    ts_min=14.0, ts_medio=20.0, ts_max=28.0,
    vs_min=78.0, vs_medio=86.0, vs_max=93.0
WHERE codigo = 'POLPA_CAFE';

-- Mucilagem de café  |  ref: https://doi.org/10.1016/j.biteb.2021.100830
UPDATE residuos SET
    bmp_min=260.0, bmp_medio=320.0, bmp_max=390.0,
    ts_min=3.0, ts_medio=8.0, ts_max=15.0,
    vs_min=82.0, vs_medio=90.0, vs_max=96.0
WHERE codigo = 'MUCILAGEM_CAFE';

-- Casca de soja  |  ref: https://doi.org/10.1016/j.wasman.2015.10.021
UPDATE residuos SET
    bmp_min=230.0, bmp_medio=300.0, bmp_max=380.0,
    ts_min=86.0, ts_medio=90.0, ts_max=93.0,
    vs_min=88.0, vs_medio=93.0, vs_max=97.0
WHERE codigo = 'CASCA_SOJA';

-- Palha de soja  |  ref: https://doi.org/10.1016/j.wasman.2015.10.021
UPDATE residuos SET
    bmp_min=150.0, bmp_medio=220.0, bmp_max=280.0,
    ts_min=80.0, ts_medio=84.0, ts_max=88.0,
    vs_min=80.0, vs_medio=85.0, vs_max=90.0
WHERE codigo = 'PALHA_SOJA';

-- Palha de milho  |  ref: https://doi.org/10.1016/j.biortech.2011.12.074
UPDATE residuos SET
    bmp_min=150.0, bmp_medio=230.0, bmp_max=300.0,
    ts_min=70.0, ts_medio=82.0, ts_max=90.0,
    vs_min=78.0, vs_medio=86.0, vs_max=92.0
WHERE codigo = 'PALHA_MILHO';

-- Casca de milho  |  ref: https://doi.org/10.1016/j.biortech.2011.12.074
UPDATE residuos SET
    bmp_min=110.0, bmp_medio=145.0, bmp_max=185.0,
    ts_min=82.0, ts_medio=88.0, ts_max=93.0,
    vs_min=78.0, vs_medio=85.0, vs_max=90.0
WHERE codigo = 'CASCA_MILHO';

-- Cama de aviário  |  ref: https://doi.org/10.1016/j.wasman.2013.10.001
UPDATE residuos SET
    bmp_min=200.0, bmp_medio=280.0, bmp_max=360.0,
    ts_min=21.25, ts_medio=25.0, ts_max=28.75,
    vs_min=62.82, vs_medio=69.8, vs_max=76.78
WHERE codigo = 'CAMA_AVIARIO';

-- Dejetos frescos de aves  |  ref: https://doi.org/10.1016/j.wasman.2013.10.001
UPDATE residuos SET
    bmp_min=150.0, bmp_medio=250.0, bmp_max=340.0,
    ts_min=5.0, ts_medio=15.0, ts_max=30.0,
    vs_min=65.0, vs_medio=75.0, vs_max=86.0
WHERE codigo = 'DEJETOS_AVES';

-- Esterco bovino  |  ref: https://doi.org/10.1016/j.biortech.2006.07.016
UPDATE residuos SET
    bmp_min=120.0, bmp_medio=200.0, bmp_max=270.0,
    ts_min=15.0, ts_medio=25.0, ts_max=35.0,
    vs_min=68.0, vs_medio=78.0, vs_max=85.0
WHERE codigo = 'ESTERCO_BOVINO';

-- Dejetos líquidos bovino  |  ref: https://doi.org/10.2134/jeq2004.0027
UPDATE residuos SET
    bmp_min=90.0, bmp_medio=155.0, bmp_max=220.0,
    ts_min=5.0, ts_medio=8.0, ts_max=12.0,
    vs_min=68.0, vs_medio=78.0, vs_max=85.0
WHERE codigo = 'DEJETOS_BOVINO';

-- Dejetos líquidos de suínos  |  ref: https://doi.org/10.2134/jeq2004.0027
UPDATE residuos SET
    bmp_min=150.0, bmp_medio=245.0, bmp_max=300.0,
    ts_min=1.5, ts_medio=3.0, ts_max=5.5,
    vs_min=70.0, vs_medio=80.0, vs_max=85.0
WHERE codigo = 'DEJETOS_SUINO';

-- Esterco sólido de suínos  |  ref: https://doi.org/10.2134/jeq2004.0027
UPDATE residuos SET
    bmp_min=150.0, bmp_medio=235.0, bmp_max=320.0,
    ts_min=20.0, ts_medio=28.0, ts_max=35.0,
    vs_min=72.0, vs_medio=83.0, vs_max=90.0
WHERE codigo = 'ESTERCO_SUINO';

-- FORSU — Fração Orgânica dos Resíduos Sólidos Urbanos separada na fonte  |  ref: https://doi.org/10.1016/j.biortech.2014.03.077
UPDATE residuos SET
    bmp_min=250.0, bmp_medio=360.0, bmp_max=500.0,
    ts_min=26.0, ts_medio=30.58, ts_max=35.17,
    vs_min=76.5, vs_medio=85.0, vs_max=93.5
WHERE codigo = 'FORSU';

-- Fração orgânica RSU  |  ref: https://doi.org/10.1016/j.biortech.2014.03.077
UPDATE residuos SET
    bmp_min=170.0, bmp_medio=270.0, bmp_max=360.0,
    ts_min=26.0, ts_medio=30.58, ts_max=35.17,
    vs_min=73.8, vs_medio=82.0, vs_max=90.2
WHERE codigo = 'ORGANICO_RSU';

-- Lodo primário de ETE  |  ref: https://doi.org/10.1016/j.wasman.2019.04.025
UPDATE residuos SET
    bmp_min=190.0, bmp_medio=310.0, bmp_max=440.0,
    ts_min=2.0, ts_medio=15.0, ts_max=30.0,
    vs_min=55.0, vs_medio=68.0, vs_max=80.0
WHERE codigo = 'LODO_PRIMARIO';

-- Lodo secundário (lodo biológico) de ETE  |  ref: https://doi.org/10.1016/j.wasman.2019.04.025
UPDATE residuos SET
    bmp_min=80.0, bmp_medio=180.0, bmp_max=260.0,
    ts_min=1.5, ts_medio=15.0, ts_max=25.0,
    vs_min=50.0, vs_medio=63.0, vs_max=75.0
WHERE codigo = 'LODO_SECUNDARIO';

-- Resíduo de poda urbana  |  ref: https://doi.org/10.1016/j.biortech.2010.09.006
UPDATE residuos SET
    bmp_min=100.0, bmp_medio=175.0, bmp_max=250.0,
    ts_min=35.0, ts_medio=55.0, ts_max=70.0,
    vs_min=75.0, vs_medio=87.0, vs_max=93.0
WHERE codigo = 'PODA_URBANA';

-- Gordura e sebo animal  |  ref: https://doi.org/10.1016/j.biortech.2014.09.072
UPDATE residuos SET
    bmp_min=700.0, bmp_medio=850.0, bmp_max=1050.0,
    ts_min=90.0, ts_medio=95.0, ts_max=99.0,
    vs_min=96.0, vs_medio=98.0, vs_max=99.5
WHERE codigo = 'GORDURA';

-- Sangue animal  |  ref: https://doi.org/10.1016/j.biortech.2014.09.072
UPDATE residuos SET
    bmp_min=300.0, bmp_medio=450.0, bmp_max=620.0,
    ts_min=15.0, ts_medio=18.0, ts_max=22.0,
    vs_min=88.0, vs_medio=93.0, vs_max=97.0
WHERE codigo = 'SANGUE';
